apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-terrakube
spec:
  secretName: letsencrypt-terrakube
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - terrakube.dorsk.dev
