apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - files:
      - files/env-config.js
    name: terrakube-ui-files
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: terrakube-ui
      app.kubernetes.io/name: terrakube-ui
