apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api
  - database
  - dex
  - executor
  - redis
  - registry
  - ui
namespace: security
configMapGenerator:
  - literals:
      - AwsEndpoint="https://minio.dorsk.dev"
      - AwsStorageRegion="us-east-1"
      - AzBuilderApiUrl="https://terrakube-api.dorsk.dev"
      - DexIssuerUri="https://terrakube-dex.dorsk.dev/dex"
      - TerrakubeEnableSecurity="true"
      - TerrakubeRedisHostname="terrakube-redis"
      - TerrakubeRedisPort="6379"
      - TerrakubeUiURL="https://terrakube.dorsk.dev"
    name: terrakube
patches:
  - patch: |
      - op: add
        path: /spec/template/metadata/annotations
        value:
          vault.security.banzaicloud.io/vault-role: "security-terrakube"
          vault.security.banzaicloud.io/vault-env-from-path: "cyberia/data/security/terrakube"
    target:
      group: apps
      kind: Deployment
      version: v1
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: terrakube
