apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-terrakube-api
spec:
  secretName: letsencrypt-terrakube-api
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - terrakube-api.dorsk.dev
