apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terrakube-database-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-retain
