apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrakube-redis
spec:
  template:
    spec:
      containers:
        - name: terrakube-redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          command: ["redis-server", "--save", "60", "1", "--loglevel warning"]
          ports:
            - name: http
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: terrakube-redis-volume
              mountPath: /data
      volumes:
        - name: terrakube-redis-volume
          emptyDir:
            sizeLimit: 1Gi
      serviceAccount: terrakube-redis
