apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - literals:
      - AwsTerraformOutputRegion="us-east-1"
      - AwsTerraformStateRegion="us-east-1"
      - ExecutorFlagBatch="false"
      - ExecutorFlagDisableAcknowledge="false"
      - TerraformOutputType="AwsTerraformOutputImpl"
      - TerraformStateType="AwsTerraformStateImpl"
      - TerrakubeApiUrl="https://terrakube-api.dorsk.dev"
      - TerrakubeRegistryDomain="terrakube-registry:8075"
      - TerrakubeToolsBranch="main"
      - TerrakubeToolsRepository="https://github.com/AzBuilder/terrakube-extensions"
    name: terrakube-executor
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: terrakube-executor
      app.kubernetes.io/name: terrakube-executor
