apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terrakube-dex
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terrakube-dex-cluster
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: terrakube-dex
subjects:
  - kind: ServiceAccount
    namespace: security
    name: terrakube-dex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: terrakube-dex
rules:
  - apiGroups: ["dex.coreos.com"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terrakube-dex
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: terrakube-dex
subjects:
  - kind: ServiceAccount
    namespace: security
    name: terrakube-dex
